(function() {
  'use strict';
  angular.module('blueconnect.mobile.directiveHtml', [])
    .constant('directiveHtml', {
      BillingHistory: '<BillingHistory billing-history="^billingHistory^"></BillingHistory>',
      BillingPaperless: '<BillingPaperless billing-paperless="^billingPaperless^"></BillingPaperless>',
      navbarMobile: '<navbar navbar-details="^navbarDetails^" geo-location-details="^geoLocationDetails^" urgent-care-details="^urgentCareDetails^"></navbar>',
      policySelectMobile: '<policy-select ng-if="showPolicySelect"></policy-select>',
      homeCardIdCard: '<home-card-id-card policy-index="^policyIndex^"></home-card-id-card>',
      homeCardBilling: '<home-card-billing payment-details="^paymentDetails^" plan-details="^planDetails^" billing-link="^billingLink^"></home-card-billing>',
      homeCardBillingError: '<home-card-billing-error plan-details="^planDetails^" error="error"></home-card-billing-error>',
      homeCardInbox: '<home-card-inbox inbox-details="^inboxDetails^"></home-card-inbox>',
      homeCardClaims: '<home-card-claims claims-title="^claimsTitle^" policy-selection="^policySelection^" claims="^claims^" total-claims="^totalClaims^"></home-card-claims>',
      tabSelect: '<tab-select tabs="^tabs^"></tab-select>',
      inboxMessageList: '<inbox-message-list messages="^messages^"></inbox-message-list>',
      inboxBottomBar: '<inbox-bottom-bar></inbox-bottom-bar>',
      inboxMessage: '<inbox-message message="^message^"></inbox-message>',
      inboxMessageBottomBar: '<inbox-message-bottom-bar message="^message^"></inbox-message-bottom-bar>',
      inboxCompose: '<inbox-compose message="^message^"></inbox-compose>',
      inboxError: '<inbox-error></inbox-error>',
      basicNavbar: '<basic-navbar navbar-details="^navbarDetails^" left-click="basicNavbarLeftClick()" right-click="basicNavbarRightClick()"></basic-navbar>',
      inboxSearch: '<inbox-search></inbox-search>',
      helpItemGroup: '<help-item-group group-details="^groupDetails^" urgent-care-details= "^urgentCareDetails^" geo-location-details= "^geoLocationDetails^"></help-item-group>',
      bottomButton: '<bottom-button button-details="^buttonDetails^"></bottom-button>',
      searchInput: '<search-input></search-input>',
      blueBarLabel: '<blue-bar-label title="^title^"></blue-bar-label>',
      listMessaging: '<list-messaging title="^title^" page-name="^pageName^"></list-messaging>',
      claimsList: '<claims-list claims="^claims^" policy-selection="^policySelection^" show-ribbon="^showRibbon^" filter-text="^filterText^" has-ccr="^hasCcr^"></claims-list>',
      memberSavingsFooter: '<member-savings-footer member-savings="^memberSavings^"></member-savings-footer>',
      claimsSearchInput: '<claims-search-input></claims-search-input>',
      claimsFilterCriteria: '<claims-filter-criteria members="^members^"></claims-filter-criteria>',
      policyHeaderGray: '<policy-header-gray></policy-header-gray>',
      policyHeaderBlue: '<policy-header-blue></policy-header-blue>',
      claimMember: '<claim-member member-name="^memberName^"></claim-member>',
      claimAmounts: '<claim-amounts amounts="^amounts^"></claim-amounts>',
      claimInfo: '<claim-info info="^info^"></claim-info>',
      claimCompose: '<claim-compose secure-message="^secureMessage^"></claim-compose>',
      idCardCustomerService: '<id-card-customer-service contact-details="^contactDetails^"></id-card-customer-service>',
      idCardInfo: '<id-card-info info="^info^"></id-card-info>',
      idCardPlanDetails: '<id-card-plan-details id-card-policy-details="^idCardPolicyDetails^"></id-card-plan-details>',
      idCardMemberDetails: '<id-card-member-details member-details="^memberDetails^"></id-card-member-details>',
      idCardImageTypes: '<id-card-image-types image-types="^imageTypes^"></id-card-image-types>',
      documentButtons: '<document-buttons buttons="^buttons^"></document-buttons>',
      claimBottomBar: '<claim-bottom-bar claim="^claim^"></claim-bottom-bar>',
      idCardNetworkDetails: '<id-card-network-details network-details="^networkDetails^"></id-card-network-details>',
      idCardBottomBar: '<id-card-bottom-bar></id-card-bottom-bar>',
      about: '<about about-details="^aboutDetails^"></about>',
      setup: '<setup data="^data^"></setup>',
      loginBottomBar: '<login-bottom-bar data="^data^"></login-bottom-bar>',
      faq: '<faq faq-details="^faqDetails^"></faq>',
      healthNav: '<health-nav health-nav-details="^healthNavDetails^"></health-nav>',
      homeCardCustomerService: '<home-card-customer-service customer-details="^customerDetails^" fad-alert-modal="^fadAlertModal^"></home-card-customer-service>',
      homeCardNewsUpdate: '<home-card-news-update news-details="^newsDetails^"></home-card-news-update>',
      homeCardInformationAlert: '<home-card-information-alert information-details="^informationDetails^"></home-card-information-alert>',
      homeCardBenefits: '<home-card-benefits selected-policy="^selectedPolicy^" policy-selection="^policySelection^" benefits="^benefits^"></home-card-benefits>',
      homeCardBenefitsSelect: '<home-card-benefits-select selected-policy="^selectedPolicy^" policy-selection="^policySelection^" benefits="^benefits^"></home-card-benefits-select>',
      benefitsDetail: '<benefits-detail benefits-data="^benefitsData^"></benefits-detail>',
      benefitsSelectDetail: '<benefits-select-detail benefits-data="^benefitsData^"></benefits-select-detail>',
      settingsList: '<settings-list settings-data="^settingsData^"></settings-list>',
      homeCardOtherLanguages: '<home-card-other-languages other-languages="^otherLanguages^"></home-card-other-languages>',
      homeCardSettings: '<home-card-settings settings="^settings^"></home-card-settings>',
      fundData: '<fund-data funds="^funds^"></fund-data>',
      idCard: '<id-card id-card-details="^idCardDetails^"></id-card>',
      verticalBarGraph: '<vertical-bar-graph graph-values="^graphValues^" graph-height="^graphHeight^"></vertical-bar-graph>',
      customerServiceCard: '<customer-service-card customer-service-card-details="^customerServiceCardDetails^" secure-inbox="^secureInbox^" localization="^localization^"></customer-service-card>',
      customerServicePhoneCard: '<customer-service-phone-card card-details="^cardDetails^" localization="^localization^" policy="^policy^"></customer-service-phone-card>',
      customerServiceSecureInbox: '<customer-service-secure-inbox customer-service-secure-inbox-details="^customerServiceSecureInboxDetails^"></customer-service-secure-inbox>',
      feedback: '<feedback data="^data^"></feedback>',
      benefitsBookletsDetails: '<benefits-booklets-details benefit-booklets="^benefitBooklets^"></benefits-booklets-details>',
      benefitsCoverageDetails: '<benefits-coverage-details policy-selection="^policySelection^" coverage-data="^coverageData^"></benefits-coverage-details>',
      medicarePlanBenefits: '<medicare-plan-benefits medicare-plan-benefits-details="^medicarePlanBenefitsDetails^"></medicare-plan-benefits>',
      medicareDrugBenefits: '<medicare-drug-benefits medicare-drug-benefits-details="^medicareDrugBenefitsDetails^"></medicare-drug-benefits>',
      medicareDrugBenefitsInitialCoverage: '<medicare-drug-benefits-initial-coverage medicare-drug-benefits-initial-coverage-details="^medicareDrugBenefitsInitialCoverageDetails^"></medicare-drug-benefits-initial-coverage>',
      medicareDrugBenefitsCoverageGap: '<medicare-drug-benefits-coverage-gap medicare-drug-benefits-coverage-gap-details="^medicareDrugBenefitsCoverageGapDetails^"></medicare-drug-benefits-coverage-gap>',
      medicareFootnotes: '<medicare-footnotes medicare-footnotes-details="^medicareFootnotesDetails^"></medicare-footnotes>',
      medicareMoreInformationPdf: '<medicare-more-information-pdf medicare-more-information-pdf-details="^medicareMoreInformationPdfDetails^"></medicare-more-information-pdf>',
      medicareSuppPlan: '<medicare-supp-plan policy="^policy^" policy-index="^policyIndex^" medicare-supp-plan-details="^medicareSuppPlanDetails^"></medicare-supp-plan>',
      medicareGroupInfo: '<medicare-group-info medicare-group-info-details="^medicareGroupInfoDetails^"></medicare-group-info>',
      billingSummary: '<billing-summary billing-details="^billingDetails^" policy="^policy^"></billing-summary>',
      billingSummaryError: '<billing-summary-error></billing-summary-error>',
      billingComingSoon: '<billing-coming-soon></billing-coming-soon>',
      billingAndPaymentsComingSoon: '<billing-and-payments-coming-soon></billing-and-payments-coming-soon>',
      billingAndPaymentsComingSoonAutopay: '<billing-and-payments-coming-soon-autopay billing-link="^billingLink^"></billing-and-payments-coming-soon-autopay>',
      prescriptionOnlyInfo: '<prescription-only-info data="^data^"></prescription-only-info>',
      paymentFlowTotalBalance: '<payment-flow-total-balance balance-info="^balanceInfo^"></payment-flow-total-balance>',
      paymentFlowTracker: '<payment-flow-tracker tracker-info="^trackerInfo^"></payment-flow-tracker>',
      trackerBillingSummary: '<tracker-billing-summary tracker-billing-data="^trackerBillingData^"></tracker-billing-summary>',
      paymentFlowPaymentFrequency: '<payment-flow-payment-frequency autopay-enrollment="^autopayEnrollment^" balance-info="^balanceInfo^" reinstatement-info="^reinstatement^"></payment-flow-payment-frequency>',
      paymentFlowPaymentMethod: '<payment-flow-payment-method method-info="^methodInfo^"></payment-flow-payment-method>',
      paymentFlowPaymentMethodSelected: '<payment-flow-payment-method-selected method-info="^methodInfo^"></payment-flow-payment-method-selected>',
      autopayFlowBillingMethod: '<autopay-flow-billing-method balance-info="^balanceInfo^"></autopay-flow-billing-method>',
      paymentFlowBillingMethod: '<payment-flow-billing-method balance-info="^balanceInfo^"></payment-flow-billing-method>',
      dentalOnlyInfo: '<dental-only-info data="^data^"></dental-only-info>',
      lowCostDentalOnlyInfo: '<low-cost-dental-only-info data="^data^" geo-location-details="^geoLocationDetails^"></low-cost-dental-only-info>',
      visionOnlyInfo: '<vision-only-info vision-benefits-data="^visionBenefitsData^"></vision-only-info>',
      contraceptiveOnlyInfo: '<contraceptive-only-info data="^data^"></contraceptive-only-info>',
      paymentFlowPaymentAmount: '<payment-flow-payment-amount account-info="^accountInfo^"></payment-flow-payment-amount>',
      paymentFlow: '<payment-flow balance-info="^balanceInfo^"></payment-flow>',
      scrollStart: '<div class="scroll-body">',
      scrollEnd: '</div>',
      paymentFlowTermsConditions: '<payment-flow-terms-conditions terms-conditions="^termsConditions^"></payment-flow-terms-conditions>',
      paymentFlowReviewDetails: '<payment-flow-review-details review-details="^reviewDetails^"></payment-flow-review-details>',
      billingPreferencesDetails: '<billing-preferences-details billing-preferences-data="^billingPreferencesData^" policy="^policy^"></billing-preferences-details>',
      billingPreferencesUpdate: '<billing-preferences-update billing-preferences-update-data="^billingPreferencesUpdateData^" policy="^policy^"></billing-preferences-update>',
      stopAutopay: '<stop-autopay token="^token^" stop-autopay-data="^stopAutopayData^" policy="^policy^"></stop-autopay>',
      paymentFlowAutoPaySuccess: '<payment-flow-auto-pay-success billing-info="^billingInfo^"></payment-flow-auto-pay-success>',
      paymentFlowAutoPaySetup: '<payment-flow-auto-pay-setup billing-info="^billingInfo^"></payment-flow-auto-pay-setup>',
      billingButtons: '<billing-buttons billing-buttons-info="^billingButtonsInfo^"></billing-buttons>',
      findDoctorNavbar: '<find-doctor-navbar navbar-details="^navbarDetails^" find-doctor-search-details="^findDoctorSearchDetails^"></find-doctor-navbar>',
      findDoctor: '<find-doctor find-doctor-details="^findDoctorDetails^" plans="^plans^"></find-doctor>',
      findCare: '<find-care find-care-details="^findCareDetails^" plans="^plans^"></find-care>',
      findDoctorSearch: '<find-doctor-search find-doctor-search-details="^findDoctorSearchDetails^" smart-shopper-details="^smartShopperDetails^"></find-doctor-search>',
      homeCardFindCare: '<home-card-find-care find-care-details="^findCareDetails^" geo-location-details = "^geoLocationDetails^" jwt="^jwt^" signature="^signature^" smart-shopper-details="^smartShopperDetails^"></home-card-find-care>',
      planSelect: '<plan-select plan-select-details="^planSelectDetails^"></plan-select>',
      findDoctorBrowser: '<find-doctor-browser find-doctor-browser-details="^findDoctorBrowserDetails^" smart-shopper-flow="^smartShopperFlow^"></find-doctor-browser>',
      findDoctorAuthenticatedNavbar: '<find-doctor-authenticated-navbar navbar-details="^navbarDetails^" find-doctor-search-details="^findDoctorSearchDetails^" urgent-care-details="^urgentCareDetails^" geo-location-details="^geoLocationDetails^"></find-doctor-authenticated-navbar>',
      findDoctorSearchBottomBar: '<find-doctor-search-bottom-bar bottom-bar-details="^bottomBarDetails^" pcp-details="^pcpDetails^"></find-doctor-search-bottom-bar>',
      findDoctorSearchResults: '<find-doctor-search-results search-results-details="^searchResultsDetails^"></find-doctor-search-results>',
      findDoctorResultsDetails: '<find-doctor-results-details find-doctor-results-details="^findDoctorResultsDetails^" smart-shopper-details="^smartShopperDetails^"></find-doctor-results-details>',
      planHeader: '<plan-header></plan-header>',
      filterDetails: '<filter-details find-doctor-filter-details="^findDoctorFilterDetails^"></filter-details>',
      homeCardChat: '<home-card-chat chat-details="^chatDetails^" live-chat-details="^liveChatDetails^"></home-card-chat>',
      homeCardPcp: '<home-card-pcp pcp-details="^pcpDetails^"></home-card-pcp>',
      pcpDependentPcps: '<pcp-dependent-pcps dependent-pcp-details="^dependentPcpDetails^"></pcp-dependent-pcps>'
    });
}());
